import React from 'react'

const ProfileHome = () => {
  return (
    <div>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
        <h1>PINTO</h1>
    </div>
  )
}

export default ProfileHome